from __future__ import annotations

from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[3]
CONFIG_DIR = Path("config")
DATA_DIR = Path("data")
RUNTIME_DIR = Path("runtime")
RUNTIME_LOG_DIR = RUNTIME_DIR / "logs"
RUNTIME_CACHE_DIR = RUNTIME_DIR / "cache"
RUNTIME_STATE_DIR = RUNTIME_DIR / "state"
RUNTIME_HISTORY_DIR = RUNTIME_DIR / "history"
RUNTIME_RAG_DIR = RUNTIME_DIR / "rag"
RUNTIME_TMP_DIR = RUNTIME_DIR / "tmp"
OLD_DIR = RUNTIME_DIR / "old"
LEGACY_LOG_DIR = OLD_DIR / "log"
AUDIO_DEBUG_DIR = RUNTIME_HISTORY_DIR / "meeting_audio_debug"
LOG_DIR = RUNTIME_LOG_DIR
PROMPTS_DIR = Path("prompts")
KNOWLEDGE_DIR = Path("knowledge")
MESSAGE_VECTOR_SQLITE_PATH = RUNTIME_RAG_DIR / "message_vectors.sqlite3"
CHANNEL_RAG_DIR = DATA_DIR / "channel_rag"
SERVER_DIR = DATA_DIR / "server"
SERVER_RAG_DIR = SERVER_DIR
SERVER_REGISTRY_SQLITE_PATH = SERVER_DIR / "server.sqlite3"
LEGACY_SCOPED_DATA_DIR = CHANNEL_RAG_DIR
ALL_EVENTS_LOG = RUNTIME_LOG_DIR / "events.log"
ALL_MESSAGES_LOG = ALL_EVENTS_LOG
SCOPED_LOG_DIR = RUNTIME_LOG_DIR / "server"
LEGACY_SCOPED_LOG_DIR = RUNTIME_LOG_DIR / "channel_rag"
RUNTIME_SETTINGS_PATH = CONFIG_DIR / "bot_settings.yaml"
LEGACY_RUNTIME_SETTINGS_PATH = DATA_DIR / "bot_settings.yaml"

for path in (
    CONFIG_DIR,
    DATA_DIR,
    RUNTIME_DIR,
    RUNTIME_LOG_DIR,
    RUNTIME_CACHE_DIR,
    RUNTIME_STATE_DIR,
    RUNTIME_HISTORY_DIR,
    RUNTIME_RAG_DIR,
    RUNTIME_TMP_DIR,
    OLD_DIR,
    AUDIO_DEBUG_DIR,
    LOG_DIR,
    SCOPED_LOG_DIR,
    LEGACY_SCOPED_LOG_DIR,
    SERVER_DIR,
    PROMPTS_DIR,
    KNOWLEDGE_DIR,
):
    path.mkdir(parents=True, exist_ok=True)

LOG_FILE = ALL_EVENTS_LOG

# Backward-compatible aliases. Prefer the explicit *_SQLITE_PATH names in new code.
MESSAGE_VECTOR_DB_PATH = MESSAGE_VECTOR_SQLITE_PATH
SERVER_DB_PATH = SERVER_REGISTRY_SQLITE_PATH
